name: schools_app
description: "" # TODO: Fill in description
# x-release-please-start-version
version: 1.1.0
# x-release-please-end
homepage: null
publish_to: none

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  accounts_library:
    git: 
      url: https://github.com/MathGaps/accounts-library.git
      ref: v1.4.x
  algolia: ^1.0.0+1
  assessments:
    path: ./features/assessments
  students:
    path: ./features/students
  pre_signup:
    path: ./features/pre_signup
  auto_size_text: ^3.0.0-nullsafety.0
  core:
    git:
      url: https://github.com/MathGaps/legacy-frontend.git
      path: packages/core
  core_dart:
    git: https://github.com/MathGaps/core-dart.git
  core_flutter:
    git: 
      url: https://github.com/MathGaps/core-flutter.git
      ref: v1.10.x
  components:
    git: 
      url: https://github.com/MathGaps/components.git
  copy_with_extension: ^4.0.0
  dartx: ^1.0.0
  equatable: ^2.0.3
  firebase_auth: 4.2.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_portal: ^1.1.0
  flutter_svg: ^1.0.0
  flutter_typeahead: 4.1.1
  go_router: 6.0.4
  injectable: 1.5.3
  url_launcher: ^6.1.2
  intl: ^0.17.0
  shared_preferences: ^2.0.15
  learn:
    git:
      url: https://github.com/MathGaps/learning-library.git
      path: features/learn
      ref: v1.16.x
  testing: 
    git:
      url: https://github.com/MathGaps/learning-library.git
      path: features/testing
      ref: v1.16.x
  skill_info: 
    git:
      url: https://github.com/MathGaps/learning-library.git
      path: features/skill_info
      ref: v1.16.x
  oxidized:
    git: https://github.com/rlch/oxidized.git
  recase: ^4.0.0
  rxdart: ^0.27.2
  schema:
    git:
      url: https://github.com/MathGaps/schema.git
      ref: v1.x
  youtube_player_iframe: ^4.0.4
  learning_library:
    git: 
      url: https://github.com/MathGaps/learning-library.git
      ref: v1.16.x

dev_dependencies:
  build_runner: 2.3.2
  copy_with_extension_gen: ^4.0.0
  dart_code_metrics: 4.19.2
  injectable_generator: 1.5.4
  flutter_lints: 2.0.0
  flutter_test:
    sdk: flutter
  graphql_codegen:
    git:
      url: https://github.com/MathGaps/graphql_codegen.git
      path: packages/graphql_codegen
      ref: package-scopes
  graphql_codegen_sanitizer:
    git: https://github.com/MathGaps/graphql_codegen_sanitizer.git
  

flutter:
  uses-material-design: true
  assets:
    - packages/schools_app/assets/sidebar_icons/curriculum.svg
    - packages/schools_app/assets/sidebar_icons/assessments.svg
    - packages/schools_app/assets/sidebar_icons/students.svg
    - packages/schools_app/assets/sidebar_icons/statistics.svg
    - packages/schools_app/assets/sidebar_icons/learning_tasks.svg
    - packages/schools_app/assets/add_class_icon.svg
    - packages/schools_app/assets/settings_icon.svg
    - packages/schools_app/assets/all_student_icon.svg
    - packages/schools_app/assets/link.png
    - packages/schools_app/assets/copy.svg
    - packages/schools_app/assets/world.svg
    - packages/schools_app/assets/help.svg
    - packages/schools_app/assets/full_logo.png
    - packages/schools_app/assets/google_logo.svg
    - packages/schools_app/assets/back_arrow.svg
    - packages/schools_app/assets/mail_icon.svg


  fonts:
    - family: Poppins
      fonts:
        - asset: google_fonts/Poppins-Thin.ttf
          weight: 100
        - asset: google_fonts/Poppins-ExtraLight.ttf
          weight: 200
        - asset: google_fonts/Poppins-Light.ttf
          weight: 300
        - asset: google_fonts/Poppins-Regular.ttf
        - asset: google_fonts/Poppins-Medium.ttf
          weight: 500
        - asset: google_fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: google_fonts/Poppins-Bold.ttf
          weight: 700
        - asset: google_fonts/Poppins-ExtraBold.ttf
          weight: 800
        - asset: google_fonts/Poppins-Black.ttf
          weight: 900
    - family: NotoColorEmoji
      fonts:
        - asset: google_fonts/NotoColorEmoji.ttf

graphql_codegen_sanitizer:
  schema_file: package:schema/src/tutero_graph.graphql.dart
