name: pre_signup
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  schools_app:
    path: ../../.
  accounts_library:
    git: 
      url: https://github.com/MathGaps/accounts-library.git
      ref: v1.4.x
  core:
    git:
      url: https://github.com/MathGaps/legacy-frontend.git
      path: packages/core
  core_flutter:
    git:
      url: https://github.com/MathGaps/core-flutter.git
      ref: v1.10.x
  schema:
    git: 
      url: https://github.com/MathGaps/schema.git
      ref: v1.x
  components:
    git:
      url: https://github.com/MathGaps/components.git
  learn:
    git:
      url: https://github.com/MathGaps/learning-library.git
      path: features/learn
      ref: v1.16.x
  skill_info: 
    git:
      url: https://github.com/MathGaps/learning-library.git
      path: features/skill_info
      ref: v1.16.x
  oxidized:
    git: https://github.com/rlch/oxidized.git
  flutter_bloc: 8.1.3
  go_router: 6.0.4
  injectable: 1.5.3
  equatable: 2.0.5

dev_dependencies:
  build_runner: 2.2.0
  graphql_codegen:
    git:
      url: https://github.com/MathGaps/graphql_codegen.git
      path: packages/graphql_codegen
      ref: package-scopes
  graphql_codegen_sanitizer:
    git: https://github.com/MathGaps/graphql_codegen_sanitizer.git
  injectable_generator: 1.5.4
  flutter_lints: 2.0.0
  copy_with_extension_gen: ^4.0.0
  dependency_validator: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - packages/pre_signup/assets/wave_emoji.png
    - packages/pre_signup/assets/year_arrow.svg
    - packages/pre_signup/assets/select_year_arrow.png
    - packages/pre_signup/assets/select_topic_arrow.png

graphql_codegen_sanitizer:
  schema_file: package:schema/src/tutero_graph.graphql.dart
