name: Example workflow
on:
  pull_request_target:
    types: "*"
  pull_request:
    types: "*"
jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "${{toJSON(github.event)}}"

