name: Preview Link Dispatch
on:
  issue_comment:
    types: [ created ]
  repository_dispatch:
    types: [ preview-command ]
jobs:
  handle-command:
    if: github.event_name == 'issue_comment' && github.event.issue.pull_request
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.REPO_ADMIN_TOKEN }}
      - uses: rickstaa/action-create-tag@v1
        with:
          tag: "pr-${{ github.event.issue.number }}"
          force_push_tag: true
      - uses: peter-evans/slash-command-dispatch@v3
        with:
          token: ${{ secrets.REPO_ADMIN_TOKEN }}
          reaction-token: ${{ secrets.REPO_ADMIN_TOKEN }}
          commands: |
            preview
          static-args: pr=${{ github.event.issue.number }}
      - uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.REPO_ADMIN_TOKEN }}
          labels: preview-link
  create-preview-link:
    runs-on: ubuntu-latest
    if: github.event_name == 'repository_dispatch'
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - uses: actions/checkout@v3
      - name: Authenticate to gcloud
        uses: google-github-actions/auth@v1
        with:
          token_format: "access_token"
          credentials_json: ${{secrets.SERVICE_ACCOUNT}}
      - name: Authenticate to GKE
        uses: google-github-actions/get-gke-credentials@7fc16a541c2f6d70a3892ef4e1cc636bfad1b221
        with:
          cluster_name: test-cluster
          location: asia-south1-a
      - run: |
          echo "apiVersion: tutero.com/v1
          kind: PreviewLink
          metadata:
            name: schools-app-example-${{ github.event.client_payload.slash_command.args.named.pr }}
            namespace: schools
          spec:
            duration: ${{ github.event.client_payload.slash_command.args.unnamed.arg1 }}
            pr: ${{ github.event.client_payload.slash_command.args.named.pr }}
            repository: schools-app-example
            githubCommentsSecretName: ${{ secrets.REPO_ADMIN_TOKEN }}
            values:
              webapp:
                subdomains:
                  - schools-app-${{ github.event.client_payload.slash_command.args.named.pr }}
                image:
                  tag: pr-${{ github.event.client_payload.slash_command.args.named.pr }}
          " >> preview-link.yml
          kubectl apply -f preview-link.yml
