name: Teardown Preview Link
on:
  pull_request:
    types:
      - closed
jobs:
  teardown:
    if: contains(github.event.pull_request.labels.*.name, 'preview-link')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Authenticate to gcloud
        uses: google-github-actions/auth@v1
        with:
          token_format: "access_token"
          credentials_json: ${{ secrets.SERVICE_ACCOUNT }}
      - name: Authenticate to GKE
        uses: google-github-actions/get-gke-credentials@7fc16a541c2f6d70a3892ef4e1cc636bfad1b221
        with:
          cluster_name: test-cluster
          location: asia-south1-a
      - run: |
          kubectl delete PreviewLink schools-app-example-${{ github.event.pull_request.number }} -n schools
